version: '2.4'
services:
  cassandradb:
    image: cassandra_image:v1
    container_name: cassandravm
    restart: always
    ports:
      - "9042:9042"
      - "9160:9160"
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "[ $$(/opt/apache-cassandra-2.0.17/bin/nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 5  
  xconfdata:
    image: xconfdata_image:v1
    container_name: xconfdatavm
    restart: always
    depends_on: 
      cassandradb:
        condition: service_healthy
    links:
      - "cassandradb:cassandravm"
    ports: 
      - "9092:9092"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:9092/queries/environments"]
      interval: 30s
      timeout: 10s
      retries: 10
  xconfadmin:
    image: xconfadmin_image:v1
    container_name: xconfadminvm
    restart: always
    depends_on: 
      xconfdata:
        condition: service_healthy
    links:
      - "cassandradb:cassandravm"
    ports: 
      - "9093:9093"
volumes:
  cassandra_data:
    name: cassandra_data
    external: true

